# Generated by Django 5.0.1 on 2024-01-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.BigIntegerField(),
        ),
    ]
